CREATE TABLE plant_identifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url VARCHAR(2048) NOT NULL,
    scientific_name VARCHAR(255),
    popular_name VARCHAR(255),
    species VARCHAR(255),
    genus VARCHAR(255),
    origin_continent VARCHAR(255),
    light_requirement VARCHAR(500),
    watering_requirement VARCHAR(500),
    healthy_appearance BOOLEAN,
    care_recommendation TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
