CREATE TABLE plantas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_cientifico VARCHAR(255) NOT NULL,
    nome_popular VARCHAR(255),
    genero VARCHAR(255),
    especie VARCHAR(255),
    continente_origem VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_plantas_nome_cientifico UNIQUE (nome_cientifico)
);

CREATE INDEX idx_plantas_nome_cientifico ON plantas (nome_cientifico);

CREATE TABLE cuidados_planta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planta_id BIGINT NOT NULL REFERENCES plantas (id),
    luminosidade_ideal VARCHAR(500),
    rega VARCHAR(255),
    frequencia_rega VARCHAR(255),
    umidade_min INTEGER,
    umidade_max INTEGER,
    temperatura_min DOUBLE PRECISION,
    temperatura_max DOUBLE PRECISION,
    tipo_solo VARCHAR(255),
    drenagem VARCHAR(255),
    observacoes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_cuidados_planta_planta_id UNIQUE (planta_id)
);
