CREATE TABLE condicoes_ambientais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    temperatura_atual DOUBLE PRECISION,
    umidade_atual DOUBLE PRECISION,
    precipitacao_mm DOUBLE PRECISION,
    indice_uv DOUBLE PRECISION,
    velocidade_vento DOUBLE PRECISION,
    descricao_clima VARCHAR(255),
    chovendo_agora BOOLEAN,
    consultado_em TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_condicoes_ambientais_lat_lon_data
    ON condicoes_ambientais (latitude, longitude, consultado_em);
