CREATE TABLE analises_planta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planta_id BIGINT NOT NULL REFERENCES plantas (id),
    identification_id BIGINT NOT NULL REFERENCES plant_identifications (id),
    condicao_ambiental_id BIGINT REFERENCES condicoes_ambientais (id),
    image_url VARCHAR(2048) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE analise_recomendacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analise_id BIGINT NOT NULL REFERENCES analises_planta (id),
    recomendacao_ordem INTEGER NOT NULL,
    categoria VARCHAR(50) NOT NULL,
    nivel VARCHAR(50) NOT NULL,
    mensagem TEXT NOT NULL
);

CREATE INDEX idx_analises_planta_planta_id ON analises_planta (planta_id);
